update for Phoenix 1.6
elpikel/ebisu pull request #1
Opened 2022-01-22 20:00 UTC by netProphET

With an interest in crypto trading and learning Phoenix, this was a great opportunity for me to try upgrading an application to 1.6. I basically fumbled my way through this, so if I've done anything that is a bad practice for an Elixir or Phoenix PR, please let me know. I did get it working though ;-)

2022-01-24 08:26 UTC, elpikel requested changes
Great work! There are two things that can be improved.

2022-01-24 08:26 UTC, elpikel commented on lib/ebisu_web/live/ticker_live.ex
> +  alias Poison
This is not used.

2022-01-24 08:26 UTC, elpikel commented on config/dev.exs
> +import Config
Please also update `config/test.exs`.

2022-01-24 18:55 UTC, netProphET commented
Thanks for catching those. There are still a few tests that aren't passing. I am not proficient in Elixir/Phoenix testing methodology just yet, but am willing to dive in and figure it out if you would prefer for the PR to include all tests passing.

2022-01-25 07:15 UTC, elpikel commented
Failing tests are calling external api, which has changed - so it is good that they are failing.

2022-01-25 07:15 UTC, merged